# Config file for automatic testing at travis-ci.org

language: python
services:
  - postgresql
  - redis-server
matrix:
    include:
      - python: 3.6
        env: TOXENV=py36

install:
  - pip install -U tox-travis coveralls
  - pip install -r requirements_dev.txt

before_script:
  - psql -c 'create database defaultdb;' -U postgres
  # - gunicorn tests.service:__hug_wsgi__ -b 127.0.0.1:9001  -p tests/run/app.pid -D
  - hug -f tests/service.py &
  - sleep 10

script: tox

after_success:
  - kill -9 `cat tests/run/app/pid`
  - coveralls
