# Config file for automatic testing at travis-ci.org

language: python
services:
  - postgresql
  - redis
matrix:
    include:
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.6
        env: TOXENV=flake8

install:
  - pip install -U tox-travis coveralls

before_script:
  - psql -c 'create database defaultdb;' -U postgres

script: tox

after_success:
  - coveralls
